import { APIGatewayProxyHandler, APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import { DynamoDBClient, QueryCommand, UpdateItemCommand } from '@aws-sdk/client-dynamodb';
import { marshall, unmarshall } from '@aws-sdk/util-dynamodb';
import { logger } from '../../utils/logger';
import { getConfig } from '../../utils/config';

const dynamoDBClient = new DynamoDBClient({});

const CORS_HEADERS = {
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': '*',
};

/**
 * Seller Insight from DynamoDB
 */
interface SellerInsight {
  id: string;
  sellerId: string;
  productId: string;
  insightType: 'pricing_recommendation' | 'dead_stock_alert' | 'market_trend';
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  actionRecommended: string;
  suggestedDiscountPercent?: number;
  suggestedPriceIncrease?: number;
  marketInsights?: string;
  status: 'pending' | 'approved' | 'rejected' | 'applied' | 'dismissed';
  createdAt: string;
  expiresAt: string;
  dismissedAt?: string;
}

/**
 * Get Insights Handler
 *
 * Fetches AI-generated insights for a seller from DynamoDB.
 * Insights are generated by the trend-analyzer-worker and stored with:
 * - PK: SELLER#{sellerId}
 * - SK: INSIGHT#{insightId}
 *
 * Query Parameters:
 * - status: Filter by status (pending, approved, rejected, applied, dismissed)
 * - pageSize: Number of results to return (default: 20, max: 100)
 *
 * POST /seller/insights/:insightId/dismiss — Dismiss an insight (sets dismissedAt)
 * POST /seller/insights/:insightId/recover — Recover a dismissed insight within 24h
 *
 * Authorization: Requires valid JWT token with seller or admin role
 */
export const handler: APIGatewayProxyHandler = async (
  event: APIGatewayProxyEvent
): Promise<APIGatewayProxyResult> => {
  const requestId = event.requestContext.requestId;

  logger.info('Get insights request received', {
    requestId,
    path: event.path,
    method: event.httpMethod,
    queryParams: event.queryStringParameters,
  });

  try {
    const sellerId = extractSellerIdFromEvent(event);

    if (!sellerId) {
      return respond(401, { error: 'Unauthorized', message: 'Seller ID not found in token' });
    }

    const config = await getConfig();

    // Route based on HTTP method and path
    if (event.httpMethod === 'POST' && event.path.endsWith('/dismiss')) {
      return handleDismiss(config.tableName, sellerId, event);
    }

    if (event.httpMethod === 'POST' && event.path.endsWith('/recover')) {
      return handleRecover(config.tableName, sellerId, event);
    }

    // Default: GET list
    const statusFilter = event.queryStringParameters?.status || 'PENDING';
    const pageSize = Math.min(
      parseInt(event.queryStringParameters?.pageSize || '20', 10),
      100
    );

    const insights = await queryInsights(config.tableName, sellerId, statusFilter, pageSize);

    return respond(200, { insights, total: insights.length, page: 1, pageSize });
  } catch (error) {
    logger.error('Failed to get insights', {
      requestId,
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
    });

    return respond(500, { error: 'Internal Server Error', message: 'Failed to retrieve insights' });
  }
};

/**
 * Dismiss an insight — sets status to 'dismissed' and records dismissedAt timestamp.
 * The insight can be recovered within 24 hours.
 */
async function handleDismiss(
  tableName: string,
  sellerId: string,
  event: APIGatewayProxyEvent
): Promise<APIGatewayProxyResult> {
  const insightId = extractInsightIdFromPath(event.path, '/dismiss');
  if (!insightId) {
    return respond(400, { error: 'Bad Request', message: 'Insight ID is required' });
  }

  const now = new Date().toISOString();

  try {
    const command = new UpdateItemCommand({
      TableName: tableName,
      Key: marshall({ PK: `SELLER#${sellerId}`, SK: `INSIGHT#${insightId}` }),
      UpdateExpression: 'SET #status = :dismissed, dismissedAt = :now, updatedAt = :now',
      ExpressionAttributeNames: { '#status': 'status' },
      ExpressionAttributeValues: marshall({ ':dismissed': 'dismissed', ':now': now, ':pending': 'pending' }),
      ConditionExpression: '#status = :pending',
      ReturnValues: 'ALL_NEW',
    });

    const response = await dynamoDBClient.send(command);
    const insight = response.Attributes ? unmarshall(response.Attributes) : null;

    logger.info('Insight dismissed', { sellerId, insightId });
    return respond(200, { success: true, insight, message: 'Insight dismissed. You can undo this within 24 hours.' });
  } catch (error) {
    if (error instanceof Error && error.name === 'ConditionalCheckFailedException') {
      return respond(400, { error: 'Bad Request', message: 'Insight is not in pending status' });
    }
    throw error;
  }
}

/**
 * Recover a dismissed insight — restores status to 'pending' if within 24h of dismissal.
 */
async function handleRecover(
  tableName: string,
  sellerId: string,
  event: APIGatewayProxyEvent
): Promise<APIGatewayProxyResult> {
  const insightId = extractInsightIdFromPath(event.path, '/recover');
  if (!insightId) {
    return respond(400, { error: 'Bad Request', message: 'Insight ID is required' });
  }

  const now = new Date();
  const twentyFourHoursAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString();

  try {
    const command = new UpdateItemCommand({
      TableName: tableName,
      Key: marshall({ PK: `SELLER#${sellerId}`, SK: `INSIGHT#${insightId}` }),
      UpdateExpression: 'SET #status = :pending, updatedAt = :now REMOVE dismissedAt',
      ExpressionAttributeNames: { '#status': 'status' },
      ExpressionAttributeValues: marshall({
        ':pending': 'pending',
        ':now': now.toISOString(),
        ':dismissed': 'dismissed',
        ':cutoff': twentyFourHoursAgo,
      }),
      ConditionExpression: '#status = :dismissed AND dismissedAt >= :cutoff',
      ReturnValues: 'ALL_NEW',
    });

    const response = await dynamoDBClient.send(command);
    const insight = response.Attributes ? unmarshall(response.Attributes) : null;

    logger.info('Insight recovered', { sellerId, insightId });
    return respond(200, { success: true, insight, message: 'Insight recovered successfully.' });
  } catch (error) {
    if (error instanceof Error && error.name === 'ConditionalCheckFailedException') {
      return respond(400, {
        error: 'Bad Request',
        message: 'Insight cannot be recovered. It may not be dismissed or the 24-hour recovery window has expired.',
      });
    }
    throw error;
  }
}

/** Extract insight ID from path like /seller/insights/{id}/dismiss */
function extractInsightIdFromPath(path: string, suffix: string): string | null {
  const cleaned = path.replace(suffix, '');
  const parts = cleaned.split('/').filter(Boolean);
  return parts[parts.length - 1] || null;
}

function respond(statusCode: number, body: Record<string, unknown>): APIGatewayProxyResult {
  return { statusCode, headers: CORS_HEADERS, body: JSON.stringify(body) };
}

/**
 * Extract seller ID from API Gateway event
 */
function extractSellerIdFromEvent(event: APIGatewayProxyEvent): string | null {
  const authorizerContext = event.requestContext.authorizer;

  if (authorizerContext) {
    const claims = authorizerContext.claims || authorizerContext;
    if (claims['custom:userId']) return claims['custom:userId'];
    if (claims.sub) return claims.sub;
  }

  const userIdHeader = event.headers['x-user-id'] || event.headers['X-User-Id'];
  if (userIdHeader) return userIdHeader;

  return null;
}

/**
 * Query insights from DynamoDB for a specific seller
 */
async function queryInsights(
  tableName: string,
  sellerId: string,
  statusFilter: string,
  limit: number
): Promise<SellerInsight[]> {
  const insights: SellerInsight[] = [];

  try {
    const statuses = statusFilter.split(',').map(s => s.trim().toLowerCase());

    const command = new QueryCommand({
      TableName: tableName,
      KeyConditionExpression: 'PK = :pk AND begins_with(SK, :sk)',
      ExpressionAttributeValues: {
        ':pk': { S: `SELLER#${sellerId}` },
        ':sk': { S: 'INSIGHT#' },
      },
      ScanIndexForward: false,
      Limit: limit * 2,
    });

    const response = await dynamoDBClient.send(command);

    if (response.Items) {
      for (const item of response.Items) {
        const insight = unmarshall(item) as SellerInsight;

        if (statuses.includes(insight.status.toLowerCase())) {
          insights.push(insight);
          if (insights.length >= limit) break;
        }
      }
    }

    return insights;
  } catch (error) {
    logger.error('Failed to query insights from DynamoDB', {
      sellerId,
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}
