import { APIGatewayProxyHandler, APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import { DynamoDBClient, QueryCommand } from '@aws-sdk/client-dynamodb';
import { unmarshall } from '@aws-sdk/util-dynamodb';
import { logger } from '../../utils/logger';
import { getConfig } from '../../utils/config';

const dynamoDBClient = new DynamoDBClient({});

/**
 * Seller Insight from DynamoDB
 */
interface SellerInsight {
  id: string;
  sellerId: string;
  productId: string;
  insightType: 'pricing_recommendation' | 'dead_stock_alert' | 'market_trend';
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  actionRecommended: string;
  suggestedDiscountPercent?: number;
  suggestedPriceIncrease?: number;
  marketInsights?: string;
  status: 'pending' | 'approved' | 'rejected' | 'applied';
  createdAt: string;
  expiresAt: string;
}

/**
 * Get Insights Handler
 * 
 * Fetches AI-generated insights for a seller from DynamoDB.
 * Insights are generated by the trend-analyzer-worker and stored with:
 * - PK: SELLER#{sellerId}
 * - SK: INSIGHT#{insightId}
 * 
 * Query Parameters:
 * - status: Filter by status (pending, approved, rejected, applied)
 * - pageSize: Number of results to return (default: 20, max: 100)
 * 
 * Authorization: Requires valid JWT token with seller or admin role
 */
export const handler: APIGatewayProxyHandler = async (
  event: APIGatewayProxyEvent
): Promise<APIGatewayProxyResult> => {
  const requestId = event.requestContext.requestId;
  
  logger.info('Get insights request received', {
    requestId,
    path: event.path,
    queryParams: event.queryStringParameters,
  });

  try {
    // Extract seller ID from JWT token (set by API Gateway authorizer)
    const sellerId = extractSellerIdFromEvent(event);
    
    if (!sellerId) {
      return {
        statusCode: 401,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
        body: JSON.stringify({
          error: 'Unauthorized',
          message: 'Seller ID not found in token',
        }),
      };
    }

    // Parse query parameters
    const statusFilter = event.queryStringParameters?.status || 'PENDING';
    const pageSize = Math.min(
      parseInt(event.queryStringParameters?.pageSize || '20', 10),
      100
    );

    logger.info('Querying insights', {
      sellerId,
      statusFilter,
      pageSize,
    });

    // Query insights from DynamoDB
    const config = await getConfig();
    const insights = await queryInsights(
      config.tableName,
      sellerId,
      statusFilter,
      pageSize
    );

    logger.info('Insights retrieved successfully', {
      sellerId,
      count: insights.length,
    });

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({
        insights,
        total: insights.length,
        page: 1,
        pageSize,
      }),
    };
  } catch (error) {
    logger.error('Failed to get insights', {
      requestId,
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : undefined,
    });

    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({
        error: 'Internal Server Error',
        message: 'Failed to retrieve insights',
      }),
    };
  }
};

/**
 * Extract seller ID from API Gateway event
 * The seller ID should be in the JWT token claims, set by the authorizer
 */
function extractSellerIdFromEvent(event: APIGatewayProxyEvent): string | null {
  // Check authorizer context first
  const authorizerContext = event.requestContext.authorizer;
  
  if (authorizerContext) {
    // For JWT authorizer, claims are in authorizer.claims
    const claims = authorizerContext.claims || authorizerContext;
    
    // Try to get seller ID from custom attribute
    if (claims['custom:userId']) {
      return claims['custom:userId'];
    }
    
    // Fallback to sub (Cognito user ID)
    if (claims.sub) {
      return claims.sub;
    }
  }

  // Fallback: try to extract from headers (for testing)
  const userIdHeader = event.headers['x-user-id'] || event.headers['X-User-Id'];
  if (userIdHeader) {
    return userIdHeader;
  }

  return null;
}

/**
 * Query insights from DynamoDB for a specific seller
 */
async function queryInsights(
  tableName: string,
  sellerId: string,
  statusFilter: string,
  limit: number
): Promise<SellerInsight[]> {
  const insights: SellerInsight[] = [];

  try {
    // Parse status filter (can be comma-separated)
    const statuses = statusFilter.split(',').map(s => s.trim().toLowerCase());

    // Query all insights for the seller
    const command = new QueryCommand({
      TableName: tableName,
      KeyConditionExpression: 'PK = :pk AND begins_with(SK, :sk)',
      ExpressionAttributeValues: {
        ':pk': { S: `SELLER#${sellerId}` },
        ':sk': { S: 'INSIGHT#' },
      },
      ScanIndexForward: false, // Most recent first
      Limit: limit * 2, // Query more to account for filtering
    });

    const response = await dynamoDBClient.send(command);

    if (response.Items) {
      for (const item of response.Items) {
        const insight = unmarshall(item) as SellerInsight;
        
        // Filter by status
        if (statuses.includes(insight.status.toLowerCase())) {
          insights.push(insight);
          
          // Stop if we have enough results
          if (insights.length >= limit) {
            break;
          }
        }
      }
    }

    return insights;
  } catch (error) {
    logger.error('Failed to query insights from DynamoDB', {
      sellerId,
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}
